/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mike' at '3/25/17 1:51 PM' with Gradle 2.14.1
 *
 * @author mike, @date 3/25/17 1:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
